using System;
using System.Collections.Generic;

namespace erpcore.entities
{
    public partial class EbayOrder
    {
        public int EbayId { get; set; }
        public string EbayOrdersn { get; set; }
        public string EbayOrderqk { get; set; }
        public string EbayPaystatus { get; set; }
        public string Recordnumber { get; set; }
        public string EbayTid { get; set; }
        public string EbayPtid { get; set; }
        public string EbayOrderid { get; set; }
        public int? EbayCreatedtime { get; set; }
        public string EbayPaidtime { get; set; }
        public string EbayUserid { get; set; }
        public string EbayUsername { get; set; }
        public string EbayUsermail { get; set; }
        public string EbayStreet { get; set; }
        public string EbayStreet1 { get; set; }
        public string EbayCity { get; set; }
        public string EbayState { get; set; }
        public string EbayCouny { get; set; }
        public string EbayCountryname { get; set; }
        public string EbayPostcode { get; set; }
        public string EbayPhone { get; set; }
        public string EbayCurrency { get; set; }
        public double? EbayTotal { get; set; }
        public int? EbayStatus { get; set; }
        public string EbayUser { get; set; }
        public int? EbayAddtime { get; set; }
        public string EbayShipfee { get; set; }
        public string EbayCombine { get; set; }
        public string Market { get; set; }
        public string EbayAccount { get; set; }
        public string EbayNote { get; set; }
        public string EbayNoteb { get; set; }
        public int? IsReg { get; set; }
        public string Ordertype { get; set; }
        public string Status { get; set; }
        public string Mailstatus { get; set; }
        public string Templateid { get; set; }
        public string Postive { get; set; }
        public string EbayCarrier { get; set; }
        public string EbayCarrier2 { get; set; }
        public string EbayCarrierstyle { get; set; }
        public string EbayWarehouse { get; set; }
        public string EbayMarkettime { get; set; }
        public string EbayTracknumber { get; set; }
        public string EbayTracknumber2 { get; set; }
        public string EbaySite { get; set; }
        public string Location { get; set; }
        public string EBayPaymentStatus { get; set; }
        public string PayPalEmailAddress { get; set; }
        public string ShippedTime { get; set; }
        public int? RefundAmount { get; set; }
        public string Resendreason { get; set; }
        public string Refundreason { get; set; }
        public int? Resendtime { get; set; }
        public int? Refundtime { get; set; }
        public int? Canceltime { get; set; }
        public string Cancelreason { get; set; }
        public int? EbayFeedback { get; set; }
        public string EbaySdsn { get; set; }
        public int? Isprint { get; set; }
        public int Ispro { get; set; }
        public string EbayOrdertype { get; set; }
        public int? Profitstatus { get; set; }
        public float? Orderweight { get; set; }
        public float? Orderweight2 { get; set; }
        public float? Ordershipfee { get; set; }
        public float? Ordercopst { get; set; }
        public int? Scantime { get; set; }
        public int? Ishide { get; set; }
        public string Packingtype { get; set; }
        public string Packinguser { get; set; }
        public string Packagingstaff { get; set; }
        public string OrderNo { get; set; }
        public string EbayPhone1 { get; set; }
        public int? Ismodifive { get; set; }
        public float? Totalprofit { get; set; }
        public int EbayCase { get; set; }
        public int PaypalCase { get; set; }
        public int Moneyback { get; set; }
        public float MoneybackTotal { get; set; }
        public int OrdersPcaseTime { get; set; }
        public int OrdersEcaseTime { get; set; }
        public int ErpOpId { get; set; }
        public string CustomPaypalemailaddress { get; set; }
        public string Pxorderid { get; set; }
        public string Pxordertime { get; set; }
        public string IsYichang { get; set; }
        public float? ShipfeeEstimate { get; set; }
        public float? Discount { get; set; }
        public string EbayAccount2 { get; set; }
    }
}
